// README 에 쓰는 화면 사진을 docs/ 에 새로 찍습니다:  node tools/screens.mjs
import { chromium } from 'playwright';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined });
const pg = await b.newPage({ viewport: { width: 1300, height: 860 } });
await pg.goto('file://' + path.join(root, 'index.html'));
await pg.route(/fonts\.(googleapis|gstatic)\.com/, r => r.continue().catch(() => {}));
await pg.waitForSelector('body[data-ready]');
await pg.click('#src-sample'); await pg.click('#btn-generate');
await pg.screenshot({ path: path.join(root, 'docs/script.png') });
await pg.click('#tabs button[data-tab=video]');
await pg.evaluate(() => HS.drawVideoFrame(document.getElementById('video-canvas').getContext('2d'), 1280, 720, 12, {}));
await pg.locator('#video-canvas').screenshot({ path: path.join(root, 'docs/video.png') });
await pg.evaluate(() => { HS.project.map.regions = [{ name: '조선(대략)', color: '#2f6db3', points: [[124.4, 40.1], [126.8, 41.7], [128.1, 41.9], [129.7, 42.4], [130, 42.3], [129.7, 41], [128.4, 40], [127.5, 39.3], [128.4, 38.6], [129.4, 37.1], [129.4, 35.5], [128.6, 35], [127.4, 34.6], [126.3, 34.4], [126.4, 35.6], [126.7, 36.9], [126.1, 37.7], [125.1, 37.8], [124.7, 38.7], [125.1, 39.5]] }]; HS.changed('all'); });
await pg.click('#tabs button[data-tab=map]'); await pg.waitForTimeout(300);
await pg.locator('#map-canvas').screenshot({ path: path.join(root, 'docs/map.png') });
await pg.click('#tabs button[data-tab=chalk]');
await pg.evaluate(() => { const c = document.getElementById('chalk-src').getContext('2d'); c.strokeStyle = '#222'; c.fillStyle = '#222'; c.lineWidth = 6;
  c.beginPath(); c.arc(400, 290, 140, 0, 7); c.stroke(); c.beginPath(); c.arc(345, 260, 14, 0, 7); c.fill(); c.beginPath(); c.arc(455, 260, 14, 0, 7); c.fill();
  c.beginPath(); c.arc(400, 320, 60, 0.3, 2.8); c.stroke(); c.beginPath(); c.moveTo(250, 200); c.lineTo(400, 110); c.lineTo(550, 200); c.stroke(); HS.convertChalkNow(); });
await pg.click('#chalk-to-board');
await pg.locator('#tab-chalk .grid2').screenshot({ path: path.join(root, 'docs/chalk.png') });
await pg.click('#tabs button[data-tab=board]'); await pg.waitForTimeout(300);
await pg.locator('#board-canvas').screenshot({ path: path.join(root, 'docs/board.png') });
await pg.evaluate(() => { HS.uploadSimple(); HS.project.thumb = { scene: 3, main: '임진왜란\n7년 전쟁', sub: '한국사 10분 정리', color: 'yellow', layout: 'left' }; HS.changed('upload'); });
await pg.click('#tabs button[data-tab=upload]'); await pg.waitForTimeout(400);
await pg.screenshot({ path: path.join(root, 'docs/upload.png') });
await pg.locator('#thumb-canvas').screenshot({ path: path.join(root, 'docs/thumbnail.png') });
await b.close();
